import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className='bg-slate-100' lang="en">
      <body className=''>
        <nav className='w-full p-4 bg-slate-600 flex items-center justify-between'>
          <h1 className='mb-4 text-4xl text-emerald-500'>
            <Link href="/">
              Blog App
            </Link>
          </h1>
        </nav>
        <div className="p-[50px]">
          {children}
        </div>
      </body>
    </html>
  )
}
